---
title: "Disag"
params: 
  inputDir: "gather/"
  thisDir:  "gather/"
  outputDir: "gathered/"
  fileStem: "Disag"
---

```{r KnitrOpts, echo=FALSE}
knitr::opts_knit$set(root.dir = normalizePath('../'))
knitr::opts_chunk$set(echo=TRUE, message=TRUE, warning=TRUE, error=TRUE)
```

```{r}
library(readr)
```

```{r eval = FALSE, echo=FALSE}
zipPath <- "../NCPSdisagZips/"

# selectors etc.
forLEAs <- c("32", "60", "68", "92")
forLEAsDist <- c("durham", "charmeck", "orange", "wake")
forLEAsText <- c("Durham", "Charlotte-Mecklenburg", "Orange", "Wake")

forGraphicsPaths <- c(graphicsPathDurham, graphicsPathCharmeck, graphicsPathOrange, graphicsPathWake)

forYears <- c("2013-14", "2014-15")
forSubjects <- c("EOG", "MA", "RD")
```

```{r}
strFile <- paste0(params$inputDir, "active_lea_school_district_schools_report.csv")

dfEDDIEschools1516 <- readr::read_csv(strFile)
```

```{r ListObjects}
lstObjects <- "dfEDDIEschools1516"
represtools::DescribeObjects(represtools::NamesToObjects(lstObjects))
```

```{r Save}
save(file = represtools::OutputFile(params)
     , list = lstObjects)
```
